// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA38VtiuZGz0sUwTRJQVjPtnnKq5CDEs_o',
    appId: '1:369523901500:web:e4e1920c6fc09093eaaf39',
    messagingSenderId: '369523901500',
    projectId: 'all-apps-6cf99',
    authDomain: 'all-apps-6cf99.firebaseapp.com',
    storageBucket: 'all-apps-6cf99.firebasestorage.app',
    measurementId: 'G-CL75SCJ55G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABqa_7cBQwoTXT2tW7phRsdYjZVdNBjRw',
    appId: '1:369523901500:android:3eed4429d2fde99eeaaf39',
    messagingSenderId: '369523901500',
    projectId: 'all-apps-6cf99',
    storageBucket: 'all-apps-6cf99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXRsdlIoFCoMIUeNTiDaUffQtJOg976Mw',
    appId: '1:369523901500:ios:f9e88c51c49d6a00eaaf39',
    messagingSenderId: '369523901500',
    projectId: 'all-apps-6cf99',
    storageBucket: 'all-apps-6cf99.firebasestorage.app',
    androidClientId: '369523901500-gi4vaio9bijajn2jsq6ls9cqisknt011.apps.googleusercontent.com',
    iosClientId: '369523901500-6492chtit704v3s6i16efnjfkrsmar1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTaskFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXRsdlIoFCoMIUeNTiDaUffQtJOg976Mw',
    appId: '1:369523901500:ios:f9e88c51c49d6a00eaaf39',
    messagingSenderId: '369523901500',
    projectId: 'all-apps-6cf99',
    storageBucket: 'all-apps-6cf99.firebasestorage.app',
    androidClientId: '369523901500-gi4vaio9bijajn2jsq6ls9cqisknt011.apps.googleusercontent.com',
    iosClientId: '369523901500-6492chtit704v3s6i16efnjfkrsmar1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTaskFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA38VtiuZGz0sUwTRJQVjPtnnKq5CDEs_o',
    appId: '1:369523901500:web:3734ab85ad881ee4eaaf39',
    messagingSenderId: '369523901500',
    projectId: 'all-apps-6cf99',
    authDomain: 'all-apps-6cf99.firebaseapp.com',
    storageBucket: 'all-apps-6cf99.firebasestorage.app',
    measurementId: 'G-K0C6KFEHGZ',
  );
}
